### ISSUE TITLE
con.getStatements() throws an exception after rulesets are applied

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#128]
testAdminCon.add(micah, lname, micahlname, dirgraph1);
		testAdminCon.add(micah, fname, micahfname, dirgraph1);
		testAdminCon.add(micah, developPrototypeOf, semantics, dirgraph1);
		testAdminCon.add(micah, type, sEngineer, dirgraph1);
		testAdminCon.add(micah, worksFor, ml, dirgraph1);
		
		testAdminCon.add(john, fname, johnfname,dirgraph);
		testAdminCon.add(john, lname, johnlname,dirgraph);
		testAdminCon.add(john, writeFuncSpecOf, inference, dirgraph);
		testAdminCon.add(john, type, lEngineer, dirgraph);
		testAdminCon.add(john, worksFor, ml, dirgraph);
		
		testAdminCon.add(writeFuncSpecOf, subProperty, design, dirgraph1);
		testAdminCon.add(developPrototypeOf, subProperty, design, dirgraph1);
		testAdminCon.add(design, subProperty, develop, dirgraph1);
		
		testAdminCon.add(lEngineer, subClass, engineer, dirgraph1);
		testAdminCon.add(sEngineer, subClass, engineer, dirgraph1);
		testAdminCon.add(engineer, subClass, employee, dirgraph1);
		
		String query = "select (count (?s)  as ?totalcount)  where {?s ?p ?o .} ";
		TupleQuery tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
		((MarkLogicQuery) tupleQuery).setRulesets(SPARQLRuleset.RDFS_PLUS_FULL);
		TupleQueryResult result	= tupleQuery.evaluate();
		RepositoryResult<Statement> resultg = testAdminCon.getStatements(null, null, null, true, dirgraph, dirgraph1);
		int i= 0;

		try {
			assertNotNull("Iterator should not be null", resultg);
			assertTrue("Iterator should not be empty", resultg.hasNext());
			

			while (resultg.hasNext()) {
				resultg.next();
				i++;
				
			}
		}
		finally {
			resultg.close();
		}

Running the above snippet, results in the following ClassCastException which is thrown at resultg.next(). If the ruleset is not set , testAdminCon.getStatements() runs fine.

org.openrdf.repository.RepositoryException: java.lang.ClassCastException: org.openrdf.model.impl.LiteralImpl cannot be cast to org.openrdf.model.Resource
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection$5.convert(MarkLogicRepositoryConnection.java:544)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection$5.convert(MarkLogicRepositoryConnection.java:1)
	at info.aduna.iteration.ExceptionConvertingIteration.next(ExceptionConvertingIteration.java:107)
	at org.openrdf.repository.RepositoryResult.next(RepositoryResult.java:72)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testRuleSets2(MarkLogicRepositoryConnectionTest.java:2457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassCastException: org.openrdf.model.impl.LiteralImpl cannot be cast to org.openrdf.model.Resource
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection$7.convert(MarkLogicRepositoryConnection.java:1344)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection$7.convert(MarkLogicRepositoryConnection.java:1)
	at info.aduna.iteration.ConvertingIteration.next(ConvertingIteration.java:88)
	at info.aduna.iteration.ExceptionConvertingIteration.next(ExceptionConvertingIteration.java:98)
	... 28 more

**Comment by xquery** [comment]
I am unable to replicate.

I do not understand the test in that I cannot see how setting a ruleset on one TupleQuery affects the getStatement. Maybe you mean default includeInferred set to true throws the error ?

Also, for clarity, [getStatement](http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/repository/RepositoryConnection.html#getStatements)-'Gets all statements with a specific subject, predicate and/or object from the repository' and does not further narrow down results from subsequent queries.

As this bug was reported sometime ago, it could have been some other interaction causing this .. may I ask if you can retest and confirm the problem still exists ?

**Comment by grechaw** [comment]
My guess is that it was fixed while I reworked null handling.

**Comment by srinathgit** [comment]
The issue still exists but it is not a bug in marklogic-sesame. Looking closely, I noticed that applying the ruleset, generated triples like the one below. 

{ "Dubinko"	   <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.w3.org/2000/01/rdf-schema#Resource> }

The problem is Sesame doesn't allow creating URI (or Resource) objects without ":"  (vf.createURI("Dubinko") fails) and when trying to parse  "Dubinko" as a Resource throws "java.lang.ClassCastException: org.openrdf.model.impl.LiteralImpl cannot be cast to org.openrdf.model.Resource" .

**Comment by srinathgit** [comment]
The issue is due to Sesame not allowing to create URI objects without " : " .
