### ISSUE TITLE
Wrong exceptions thrown by con.prepare*Query()

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#73]
1. As per spec, 'IllegalArgumentException' should be thrown by con.prepare*Query()
for example for  con.prepareGraphQuery() if a graph query is not provided (DESCRIBE or CONSTRUCT),  IllegalArgumentException should be thrown. Right now, a different exception is thrown whenever a wrong query is passed 
2.  If the SPARQL query has syntax errors, 'MalformedQueryException' should be thrown but right now, we throw the exception returned by the ML client.

**Comment by xquery** [comment]
fixed by #72

**Comment by srinathgit** [comment]
This issue still persists. The malformed SPARQL syntax or using con.prepareGraphQuery() to prepare a SELECT query don't throw 'MalformedQueryException' or 'IllegalArgumentException' respectively. They still throw the exception from the client.

**Comment by grechaw** [comment]
Pushed to 1.0.2 as a nice-to-have but not something to block release

**Comment by xquery** [comment]
I will keep this as a bug (not enhancement) in the hope I can pick off a few of them.

**Comment by xquery** [comment]
should handle trapping FailedRequestException for setting a bad literal

```
Literal invalidIntegerLiteral = vf.createLiteral("four", XMLSchema.INTEGER);
testAdminCon.add(micah, homeTel, invalidIntegerLiteral, dirgraph);
```

**Comment by srinathgit** [comment]
testReaderCon is an object obtained using user with only rest-reader privilege.

testReaderCon.add(st1, vf.createURI("http://abc")); 

throws "com.marklogic.client.ForbiddenUserException" . It is expected to throw "org.openrdf.query.UpdateExecutionException"

**Comment by xquery** [comment]
there is an open question if we need to emit more appropriate api level exceptions at the java api client layer to abstract away the REST layer errors.
